# Generated by Django 5.1 on 2024-08-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('guests', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
            ],
        ),
    ]
